services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_LOCAL_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
    - "${REDIS_PORT}:6379"
